# Generated by Django 3.2.4 on 2021-06-23 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seenby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_seen_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seealert',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='alert_seen_by', to='Alerts.SeenBy'),
        ),
        migrations.AddField(
            model_name='alertsrules',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='alert_target_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='alertsrules',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='alert_target_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
