# Generated by Django 3.2.4 on 2021-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsrules',
            name='filter',
            field=models.CharField(help_text='example: "oxgyn__lt=80"', max_length=30),
        ),
    ]
