# Generated by Django 3.2.4 on 2021-06-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_value_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='user',
        ),
    ]
