# Generated by Django 3.2.4 on 2021-06-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('symptom', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.symptom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='Profileother_langauge', to='patients.SymptomsHistory'),
        ),
    ]
