# Generated by Django 3.2.4 on 2021-06-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210626_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomshistory',
            name='symptom',
        ),
        migrations.AddField(
            model_name='symptomshistory',
            name='symptom',
            field=models.ManyToManyField(to='patients.Symptom'),
        ),
    ]
